# Generated by Django 5.2 on 2025-04-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_game_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('genre', 'Genre'), ('mood', 'Mood'), ('keyword', 'Keyword')], max_length=20)),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
